In [13]:
import pandas as pd

# Load the oil price data


# Load the exchange rate data
exchange = pd.read_csv('../Data/Exchange rate.csv')
macroeconomic=pd.read_csv('../Data/macroeconomic .csv')
oil=pd.read_csv('../Data/Copy of BrentOilPrices.csv')
macro
# Check unique values in the date columns
print(exchange['Date'].unique())
print(macroeconomic['Date'].unique())
print(oil['Date'].unique())
# Convert the 'Date' columns to datetime format
exchange['Date'] = pd.to_datetime(exchange['Date'])
macroeconomic['Date'] = pd.to_datetime(macroeconomic['Date'])
oil['Date'] = pd.to_datetime(oil['Date'])

['Jan-87' 'Feb-87' 'Mar-87' 'Apr-87' 'May-87' 'Jun-87' 'Jul-87' 'Aug-87'
 'Sep-87' 'Oct-87' 'Nov-87' 'Dec-87' 'Jan-88' 'Feb-88' 'Mar-88' 'Apr-88'
 'May-88' 'Jun-88' 'Jul-88' 'Aug-88' 'Sep-88' 'Oct-88' 'Nov-88' 'Dec-88'
 'Jan-89' 'Feb-89' 'Mar-89' 'Apr-89' 'May-89' 'Jun-89' 'Jul-89' 'Aug-89'
 'Sep-89' 'Oct-89' 'Nov-89' 'Dec-89' 'Jan-90' 'Feb-90' 'Mar-90' 'Apr-90'
 'May-90' 'Jun-90' 'Jul-90' 'Aug-90' 'Sep-90' 'Oct-90' 'Nov-90' 'Dec-90'
 'Jan-91' 'Feb-91' 'Mar-91' 'Apr-91' 'May-91' 'Jun-91' 'Jul-91' 'Aug-91'
 'Sep-91' 'Oct-91' 'Nov-91' 'Dec-91' 'Jan-92' 'Feb-92' 'Mar-92' 'Apr-92'
 'May-92' 'Jun-92' 'Jul-92' 'Aug-92' 'Sep-92' 'Oct-92' 'Nov-92' 'Dec-92'
 'Jan-93' 'Feb-93' 'Mar-93' 'Apr-93' 'May-93' 'Jun-93' 'Jul-93' 'Aug-93'
 'Sep-93' 'Oct-93' 'Nov-93' 'Dec-93' 'Jan-94' 'Feb-94' 'Mar-94' 'Apr-94'
 'May-94' 'Jun-94' 'Jul-94' 'Aug-94' 'Sep-94' 'Oct-94' 'Nov-94' 'Dec-94'
 'Jan-95' 'Feb-95' 'Mar-95' 'Apr-95' 'May-95' 'Jun-95' 'Jul-95' 'Aug-95'
 'Sep-95' 'Oct-95' 'Nov-95' 'Dec-95' 'Jan-96' 'Feb-96' 'Mar-96' 'Apr-96'
 'May-96' 'Jun-96' 'Jul-96' 'Aug-96' 'Sep-96' 'Oct-96' 'Nov-96' 'Dec-96'
 'Jan-97' 'Feb-97' 'Mar-97' 'Apr-97' 'May-97' 'Jun-97' 'Jul-97' 'Aug-97'
 'Sep-97' 'Oct-97' 'Nov-97' 'Dec-97' 'Jan-98' 'Feb-98' 'Mar-98' 'Apr-98'
 'May-98' 'Jun-98' 'Jul-98' 'Aug-98' 'Sep-98' 'Oct-98' 'Nov-98' 'Dec-98'
 'Jan-99' 'Feb-99' 'Mar-99' 'Apr-99' 'May-99' 'Jun-99' 'Jul-99' 'Aug-99'
 'Sep-99' 'Oct-99' 'Nov-99' 'Dec-99' 'Jan-00' 'Feb-00' 'Mar-00' 'Apr-00'
 'May-00' 'Jun-00' 'Jul-00' 'Aug-00' 'Sep-00' 'Oct-00' 'Nov-00' 'Dec-00'
 'Jan-01' 'Feb-01' 'Mar-01' 'Apr-01' 'May-01' 'Jun-01' 'Jul-01' 'Aug-01'
 'Sep-01' 'Oct-01' 'Nov-01' 'Dec-01' 'Jan-02' 'Feb-02' 'Mar-02' 'Apr-02'
 'May-02' 'Jun-02' 'Jul-02' 'Aug-02' 'Sep-02' 'Oct-02' 'Nov-02' 'Dec-02'
 'Jan-03' 'Feb-03' 'Mar-03' 'Apr-03' 'May-03' 'Jun-03' 'Jul-03' 'Aug-03'
 'Sep-03' 'Oct-03' 'Nov-03' 'Dec-03' 'Jan-04' 'Feb-04' 'Mar-04' 'Apr-04'
 'May-04' 'Jun-04' 'Jul-04' 'Aug-04' 'Sep-04' 'Oct-04' 'Nov-04' 'Dec-04'
 'Jan-05' 'Feb-05' 'Mar-05' 'Apr-05' 'May-05' 'Jun-05' 'Jul-05' 'Aug-05'
 'Sep-05' 'Oct-05' 'Nov-05' 'Dec-05' 'Jan-06' 'Feb-06' 'Mar-06' 'Apr-06'
 'May-06' 'Jun-06' 'Jul-06' 'Aug-06' 'Sep-06' 'Oct-06' 'Nov-06' 'Dec-06'
 'Jan-07' 'Feb-07' 'Mar-07' 'Apr-07' 'May-07' 'Jun-07' 'Jul-07' 'Aug-07'
 'Sep-07' 'Oct-07' 'Nov-07' 'Dec-07' 'Jan-08' 'Feb-08' 'Mar-08' 'Apr-08'
 'May-08' 'Jun-08' 'Jul-08' 'Aug-08' 'Sep-08' 'Oct-08' 'Nov-08' 'Dec-08'
 'Jan-09' 'Feb-09' 'Mar-09' 'Apr-09' 'May-09' 'Jun-09' 'Jul-09' 'Aug-09'
 'Sep-09' 'Oct-09' 'Nov-09' 'Dec-09' 'Jan-10' 'Feb-10' 'Mar-10' 'Apr-10'
 'May-10' 'Jun-10' 'Jul-10' 'Aug-10' 'Sep-10' 'Oct-10' 'Nov-10' 'Dec-10'
 'Jan-11' 'Feb-11' 'Mar-11' 'Apr-11' 'May-11' 'Jun-11' 'Jul-11' 'Aug-11'
 'Sep-11' 'Oct-11' 'Nov-11' 'Dec-11' 'Jan-12' 'Feb-12' 'Mar-12' 'Apr-12'
 'May-12' 'Jun-12' 'Jul-12' 'Aug-12' 'Sep-12' 'Oct-12' 'Nov-12' 'Dec-12'
 'Jan-13' 'Feb-13' 'Mar-13' 'Apr-13' 'May-13' 'Jun-13' 'Jul-13' 'Aug-13'
 'Sep-13' 'Oct-13' 'Nov-13' 'Dec-13' 'Jan-14' 'Feb-14' 'Mar-14' 'Apr-14'
 'May-14' 'Jun-14' 'Jul-14' 'Aug-14' 'Sep-14' 'Oct-14' 'Nov-14' 'Dec-14'
 'Jan-15' 'Feb-15' 'Mar-15' 'Apr-15' 'May-15' 'Jun-15' 'Jul-15' 'Aug-15'
 'Sep-15' 'Oct-15' 'Nov-15' 'Dec-15' 'Jan-16' 'Feb-16' 'Mar-16' 'Apr-16'
 'May-16' 'Jun-16' 'Jul-16' 'Aug-16' 'Sep-16' 'Oct-16' 'Nov-16' 'Dec-16'
 'Jan-17' 'Feb-17' 'Mar-17' 'Apr-17' 'May-17' 'Jun-17' 'Jul-17' 'Aug-17'
 'Sep-17' 'Oct-17' 'Nov-17' 'Dec-17' 'Jan-18' 'Feb-18' 'Mar-18' 'Apr-18'
 'May-18' 'Jun-18' 'Jul-18' 'Aug-18' 'Sep-18' 'Oct-18' 'Nov-18' 'Dec-18'
 'Jan-19' 'Feb-19' 'Mar-19' 'Apr-19' 'May-19' 'Jun-19' 'Jul-19' 'Aug-19'
 'Sep-19' 'Oct-19' 'Nov-19' 'Dec-19' 'Jan-20' 'Feb-20' 'Mar-20' 'Apr-20'
 'May-20' 'Jun-20' 'Jul-20' 'Aug-20' 'Sep-20' 'Oct-20' 'Nov-20' 'Dec-20'
 'Jan-21' 'Feb-21' 'Mar-21' 'Apr-21' 'May-21' 'Jun-21' 'Jul-21' 'Aug-21'
 'Sep-21' 'Oct-21' 'Nov-21' 'Dec-21' 'Jan-22' 'Feb-22' 'Mar-22' 'Apr-22'
 'May-22' 'Jun-22' 'Jul-22' 'Aug-22' 'Sep-22' 'Oct-22' 'Nov-22' 'Dec-22']
[1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000
 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014
 2015 2016 2017 2018 2019 2020 2021 2022]
['20-May-87' '21-May-87' '22-May-87' ... 'Nov 10, 2022' 'Nov 11, 2022'
 'Nov 14, 2022']

C:\Users\Addisu\AppData\Local\Temp\ipykernel_9724\2160409851.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  exchange['Date'] = pd.to_datetime(exchange['Date'])

DateParseError: day is out of range for month: Jan-00, at position 156

In [24]:
import pandas as pd

# Load datasets
exchange = pd.read_csv('../Data/Exchange rate.csv')
macroeconomic=pd.read_csv('../Data/macroeconomic .csv')
# Check unique values in the 'Date' column to confirm format
print(exchange['Date'].unique())

# Specify the date format when converting
exchange['Date'] = pd.to_datetime(exchange['Date'], format='%b-%y', errors='coerce')

# Check for any invalid dates
print(exchange[exchange['Date'].isna()])

# Drop or handle NaT values as needed
exchange.dropna(subset=['Date'], inplace=True)

['Jan-87' 'Feb-87' 'Mar-87' 'Apr-87' 'May-87' 'Jun-87' 'Jul-87' 'Aug-87'
 'Sep-87' 'Oct-87' 'Nov-87' 'Dec-87' 'Jan-88' 'Feb-88' 'Mar-88' 'Apr-88'
 'May-88' 'Jun-88' 'Jul-88' 'Aug-88' 'Sep-88' 'Oct-88' 'Nov-88' 'Dec-88'
 'Jan-89' 'Feb-89' 'Mar-89' 'Apr-89' 'May-89' 'Jun-89' 'Jul-89' 'Aug-89'
 'Sep-89' 'Oct-89' 'Nov-89' 'Dec-89' 'Jan-90' 'Feb-90' 'Mar-90' 'Apr-90'
 'May-90' 'Jun-90' 'Jul-90' 'Aug-90' 'Sep-90' 'Oct-90' 'Nov-90' 'Dec-90'
 'Jan-91' 'Feb-91' 'Mar-91' 'Apr-91' 'May-91' 'Jun-91' 'Jul-91' 'Aug-91'
 'Sep-91' 'Oct-91' 'Nov-91' 'Dec-91' 'Jan-92' 'Feb-92' 'Mar-92' 'Apr-92'
 'May-92' 'Jun-92' 'Jul-92' 'Aug-92' 'Sep-92' 'Oct-92' 'Nov-92' 'Dec-92'
 'Jan-93' 'Feb-93' 'Mar-93' 'Apr-93' 'May-93' 'Jun-93' 'Jul-93' 'Aug-93'
 'Sep-93' 'Oct-93' 'Nov-93' 'Dec-93' 'Jan-94' 'Feb-94' 'Mar-94' 'Apr-94'
 'May-94' 'Jun-94' 'Jul-94' 'Aug-94' 'Sep-94' 'Oct-94' 'Nov-94' 'Dec-94'
 'Jan-95' 'Feb-95' 'Mar-95' 'Apr-95' 'May-95' 'Jun-95' 'Jul-95' 'Aug-95'
 'Sep-95' 'Oct-95' 'Nov-95' 'Dec-95' 'Jan-96' 'Feb-96' 'Mar-96' 'Apr-96'
 'May-96' 'Jun-96' 'Jul-96' 'Aug-96' 'Sep-96' 'Oct-96' 'Nov-96' 'Dec-96'
 'Jan-97' 'Feb-97' 'Mar-97' 'Apr-97' 'May-97' 'Jun-97' 'Jul-97' 'Aug-97'
 'Sep-97' 'Oct-97' 'Nov-97' 'Dec-97' 'Jan-98' 'Feb-98' 'Mar-98' 'Apr-98'
 'May-98' 'Jun-98' 'Jul-98' 'Aug-98' 'Sep-98' 'Oct-98' 'Nov-98' 'Dec-98'
 'Jan-99' 'Feb-99' 'Mar-99' 'Apr-99' 'May-99' 'Jun-99' 'Jul-99' 'Aug-99'
 'Sep-99' 'Oct-99' 'Nov-99' 'Dec-99' 'Jan-00' 'Feb-00' 'Mar-00' 'Apr-00'
 'May-00' 'Jun-00' 'Jul-00' 'Aug-00' 'Sep-00' 'Oct-00' 'Nov-00' 'Dec-00'
 'Jan-01' 'Feb-01' 'Mar-01' 'Apr-01' 'May-01' 'Jun-01' 'Jul-01' 'Aug-01'
 'Sep-01' 'Oct-01' 'Nov-01' 'Dec-01' 'Jan-02' 'Feb-02' 'Mar-02' 'Apr-02'
 'May-02' 'Jun-02' 'Jul-02' 'Aug-02' 'Sep-02' 'Oct-02' 'Nov-02' 'Dec-02'
 'Jan-03' 'Feb-03' 'Mar-03' 'Apr-03' 'May-03' 'Jun-03' 'Jul-03' 'Aug-03'
 'Sep-03' 'Oct-03' 'Nov-03' 'Dec-03' 'Jan-04' 'Feb-04' 'Mar-04' 'Apr-04'
 'May-04' 'Jun-04' 'Jul-04' 'Aug-04' 'Sep-04' 'Oct-04' 'Nov-04' 'Dec-04'
 'Jan-05' 'Feb-05' 'Mar-05' 'Apr-05' 'May-05' 'Jun-05' 'Jul-05' 'Aug-05'
 'Sep-05' 'Oct-05' 'Nov-05' 'Dec-05' 'Jan-06' 'Feb-06' 'Mar-06' 'Apr-06'
 'May-06' 'Jun-06' 'Jul-06' 'Aug-06' 'Sep-06' 'Oct-06' 'Nov-06' 'Dec-06'
 'Jan-07' 'Feb-07' 'Mar-07' 'Apr-07' 'May-07' 'Jun-07' 'Jul-07' 'Aug-07'
 'Sep-07' 'Oct-07' 'Nov-07' 'Dec-07' 'Jan-08' 'Feb-08' 'Mar-08' 'Apr-08'
 'May-08' 'Jun-08' 'Jul-08' 'Aug-08' 'Sep-08' 'Oct-08' 'Nov-08' 'Dec-08'
 'Jan-09' 'Feb-09' 'Mar-09' 'Apr-09' 'May-09' 'Jun-09' 'Jul-09' 'Aug-09'
 'Sep-09' 'Oct-09' 'Nov-09' 'Dec-09' 'Jan-10' 'Feb-10' 'Mar-10' 'Apr-10'
 'May-10' 'Jun-10' 'Jul-10' 'Aug-10' 'Sep-10' 'Oct-10' 'Nov-10' 'Dec-10'
 'Jan-11' 'Feb-11' 'Mar-11' 'Apr-11' 'May-11' 'Jun-11' 'Jul-11' 'Aug-11'
 'Sep-11' 'Oct-11' 'Nov-11' 'Dec-11' 'Jan-12' 'Feb-12' 'Mar-12' 'Apr-12'
 'May-12' 'Jun-12' 'Jul-12' 'Aug-12' 'Sep-12' 'Oct-12' 'Nov-12' 'Dec-12'
 'Jan-13' 'Feb-13' 'Mar-13' 'Apr-13' 'May-13' 'Jun-13' 'Jul-13' 'Aug-13'
 'Sep-13' 'Oct-13' 'Nov-13' 'Dec-13' 'Jan-14' 'Feb-14' 'Mar-14' 'Apr-14'
 'May-14' 'Jun-14' 'Jul-14' 'Aug-14' 'Sep-14' 'Oct-14' 'Nov-14' 'Dec-14'
 'Jan-15' 'Feb-15' 'Mar-15' 'Apr-15' 'May-15' 'Jun-15' 'Jul-15' 'Aug-15'
 'Sep-15' 'Oct-15' 'Nov-15' 'Dec-15' 'Jan-16' 'Feb-16' 'Mar-16' 'Apr-16'
 'May-16' 'Jun-16' 'Jul-16' 'Aug-16' 'Sep-16' 'Oct-16' 'Nov-16' 'Dec-16'
 'Jan-17' 'Feb-17' 'Mar-17' 'Apr-17' 'May-17' 'Jun-17' 'Jul-17' 'Aug-17'
 'Sep-17' 'Oct-17' 'Nov-17' 'Dec-17' 'Jan-18' 'Feb-18' 'Mar-18' 'Apr-18'
 'May-18' 'Jun-18' 'Jul-18' 'Aug-18' 'Sep-18' 'Oct-18' 'Nov-18' 'Dec-18'
 'Jan-19' 'Feb-19' 'Mar-19' 'Apr-19' 'May-19' 'Jun-19' 'Jul-19' 'Aug-19'
 'Sep-19' 'Oct-19' 'Nov-19' 'Dec-19' 'Jan-20' 'Feb-20' 'Mar-20' 'Apr-20'
 'May-20' 'Jun-20' 'Jul-20' 'Aug-20' 'Sep-20' 'Oct-20' 'Nov-20' 'Dec-20'
 'Jan-21' 'Feb-21' 'Mar-21' 'Apr-21' 'May-21' 'Jun-21' 'Jul-21' 'Aug-21'
 'Sep-21' 'Oct-21' 'Nov-21' 'Dec-21' 'Jan-22' 'Feb-22' 'Mar-22' 'Apr-22'
 'May-22' 'Jun-22' 'Jul-22' 'Aug-22' 'Sep-22' 'Oct-22' 'Nov-22' 'Dec-22']
Empty DataFrame
Columns: [Date, USD for United Kingdom, USD FOR EURO, USD FOR CANADA]
Index: []

In [28]:
import pandas as pd
import pandas as pd

import pandas as pd

# Load datasets
exchange = pd.read_csv('../Data/Exchange rate.csv')
macroeconomic=pd.read_csv('../Data/macroeconomic .csv')
oil=pd.read_csv('../Data/Copy of BrentOilPrices.csv')
# Check unique values in the 'Date' column to confirm format
print(exchange['Date'].unique())

# Specify the date format when converting
exchange['Date'] = pd.to_datetime(exchange['Date'], format='%b-%y', errors='coerce')

# Check for any invalid dates
print(exchange[exchange['Date'].isna()])

# Drop or handle NaT values as needed
exchange.dropna(subset=['Date'], inplace=True)

# Convert 'Date' columns to datetime
exchange['Date'] = pd.to_datetime(exchange['Date'])
macroeconomic['Date'] = pd.to_datetime(macroeconomic['Date'])
oil['Date'] = pd.to_datetime(oil['Date'])

# Set 'Date' as index
exchange.set_index('Date', inplace=True)
macroeconomic.set_index('Date', inplace=True)
oil.set_index('Date', inplace=True)

# Resample macroeconomic data to monthly
macroeconomic_monthly = macroeconomic.resample('M').ffill()

# Merge datasets
combined_data = oil.join(exchange, how='outer').join(macroeconomic_monthly, how='outer')

# Fill missing values
combined_data.fillna(method='ffill', inplace=True)

# Inspect combined data
print(combined_data.head())


# Save the combined data to CSV
combined_data.to_csv('../Data/combined_data.csv')

['Jan-87' 'Feb-87' 'Mar-87' 'Apr-87' 'May-87' 'Jun-87' 'Jul-87' 'Aug-87'
 'Sep-87' 'Oct-87' 'Nov-87' 'Dec-87' 'Jan-88' 'Feb-88' 'Mar-88' 'Apr-88'
 'May-88' 'Jun-88' 'Jul-88' 'Aug-88' 'Sep-88' 'Oct-88' 'Nov-88' 'Dec-88'
 'Jan-89' 'Feb-89' 'Mar-89' 'Apr-89' 'May-89' 'Jun-89' 'Jul-89' 'Aug-89'
 'Sep-89' 'Oct-89' 'Nov-89' 'Dec-89' 'Jan-90' 'Feb-90' 'Mar-90' 'Apr-90'
 'May-90' 'Jun-90' 'Jul-90' 'Aug-90' 'Sep-90' 'Oct-90' 'Nov-90' 'Dec-90'
 'Jan-91' 'Feb-91' 'Mar-91' 'Apr-91' 'May-91' 'Jun-91' 'Jul-91' 'Aug-91'
 'Sep-91' 'Oct-91' 'Nov-91' 'Dec-91' 'Jan-92' 'Feb-92' 'Mar-92' 'Apr-92'
 'May-92' 'Jun-92' 'Jul-92' 'Aug-92' 'Sep-92' 'Oct-92' 'Nov-92' 'Dec-92'
 'Jan-93' 'Feb-93' 'Mar-93' 'Apr-93' 'May-93' 'Jun-93' 'Jul-93' 'Aug-93'
 'Sep-93' 'Oct-93' 'Nov-93' 'Dec-93' 'Jan-94' 'Feb-94' 'Mar-94' 'Apr-94'
 'May-94' 'Jun-94' 'Jul-94' 'Aug-94' 'Sep-94' 'Oct-94' 'Nov-94' 'Dec-94'
 'Jan-95' 'Feb-95' 'Mar-95' 'Apr-95' 'May-95' 'Jun-95' 'Jul-95' 'Aug-95'
 'Sep-95' 'Oct-95' 'Nov-95' 'Dec-95' 'Jan-96' 'Feb-96' 'Mar-96' 'Apr-96'
 'May-96' 'Jun-96' 'Jul-96' 'Aug-96' 'Sep-96' 'Oct-96' 'Nov-96' 'Dec-96'
 'Jan-97' 'Feb-97' 'Mar-97' 'Apr-97' 'May-97' 'Jun-97' 'Jul-97' 'Aug-97'
 'Sep-97' 'Oct-97' 'Nov-97' 'Dec-97' 'Jan-98' 'Feb-98' 'Mar-98' 'Apr-98'
 'May-98' 'Jun-98' 'Jul-98' 'Aug-98' 'Sep-98' 'Oct-98' 'Nov-98' 'Dec-98'
 'Jan-99' 'Feb-99' 'Mar-99' 'Apr-99' 'May-99' 'Jun-99' 'Jul-99' 'Aug-99'
 'Sep-99' 'Oct-99' 'Nov-99' 'Dec-99' 'Jan-00' 'Feb-00' 'Mar-00' 'Apr-00'
 'May-00' 'Jun-00' 'Jul-00' 'Aug-00' 'Sep-00' 'Oct-00' 'Nov-00' 'Dec-00'
 'Jan-01' 'Feb-01' 'Mar-01' 'Apr-01' 'May-01' 'Jun-01' 'Jul-01' 'Aug-01'
 'Sep-01' 'Oct-01' 'Nov-01' 'Dec-01' 'Jan-02' 'Feb-02' 'Mar-02' 'Apr-02'
 'May-02' 'Jun-02' 'Jul-02' 'Aug-02' 'Sep-02' 'Oct-02' 'Nov-02' 'Dec-02'
 'Jan-03' 'Feb-03' 'Mar-03' 'Apr-03' 'May-03' 'Jun-03' 'Jul-03' 'Aug-03'
 'Sep-03' 'Oct-03' 'Nov-03' 'Dec-03' 'Jan-04' 'Feb-04' 'Mar-04' 'Apr-04'
 'May-04' 'Jun-04' 'Jul-04' 'Aug-04' 'Sep-04' 'Oct-04' 'Nov-04' 'Dec-04'
 'Jan-05' 'Feb-05' 'Mar-05' 'Apr-05' 'May-05' 'Jun-05' 'Jul-05' 'Aug-05'
 'Sep-05' 'Oct-05' 'Nov-05' 'Dec-05' 'Jan-06' 'Feb-06' 'Mar-06' 'Apr-06'
 'May-06' 'Jun-06' 'Jul-06' 'Aug-06' 'Sep-06' 'Oct-06' 'Nov-06' 'Dec-06'
 'Jan-07' 'Feb-07' 'Mar-07' 'Apr-07' 'May-07' 'Jun-07' 'Jul-07' 'Aug-07'
 'Sep-07' 'Oct-07' 'Nov-07' 'Dec-07' 'Jan-08' 'Feb-08' 'Mar-08' 'Apr-08'
 'May-08' 'Jun-08' 'Jul-08' 'Aug-08' 'Sep-08' 'Oct-08' 'Nov-08' 'Dec-08'
 'Jan-09' 'Feb-09' 'Mar-09' 'Apr-09' 'May-09' 'Jun-09' 'Jul-09' 'Aug-09'
 'Sep-09' 'Oct-09' 'Nov-09' 'Dec-09' 'Jan-10' 'Feb-10' 'Mar-10' 'Apr-10'
 'May-10' 'Jun-10' 'Jul-10' 'Aug-10' 'Sep-10' 'Oct-10' 'Nov-10' 'Dec-10'
 'Jan-11' 'Feb-11' 'Mar-11' 'Apr-11' 'May-11' 'Jun-11' 'Jul-11' 'Aug-11'
 'Sep-11' 'Oct-11' 'Nov-11' 'Dec-11' 'Jan-12' 'Feb-12' 'Mar-12' 'Apr-12'
 'May-12' 'Jun-12' 'Jul-12' 'Aug-12' 'Sep-12' 'Oct-12' 'Nov-12' 'Dec-12'
 'Jan-13' 'Feb-13' 'Mar-13' 'Apr-13' 'May-13' 'Jun-13' 'Jul-13' 'Aug-13'
 'Sep-13' 'Oct-13' 'Nov-13' 'Dec-13' 'Jan-14' 'Feb-14' 'Mar-14' 'Apr-14'
 'May-14' 'Jun-14' 'Jul-14' 'Aug-14' 'Sep-14' 'Oct-14' 'Nov-14' 'Dec-14'
 'Jan-15' 'Feb-15' 'Mar-15' 'Apr-15' 'May-15' 'Jun-15' 'Jul-15' 'Aug-15'
 'Sep-15' 'Oct-15' 'Nov-15' 'Dec-15' 'Jan-16' 'Feb-16' 'Mar-16' 'Apr-16'
 'May-16' 'Jun-16' 'Jul-16' 'Aug-16' 'Sep-16' 'Oct-16' 'Nov-16' 'Dec-16'
 'Jan-17' 'Feb-17' 'Mar-17' 'Apr-17' 'May-17' 'Jun-17' 'Jul-17' 'Aug-17'
 'Sep-17' 'Oct-17' 'Nov-17' 'Dec-17' 'Jan-18' 'Feb-18' 'Mar-18' 'Apr-18'
 'May-18' 'Jun-18' 'Jul-18' 'Aug-18' 'Sep-18' 'Oct-18' 'Nov-18' 'Dec-18'
 'Jan-19' 'Feb-19' 'Mar-19' 'Apr-19' 'May-19' 'Jun-19' 'Jul-19' 'Aug-19'
 'Sep-19' 'Oct-19' 'Nov-19' 'Dec-19' 'Jan-20' 'Feb-20' 'Mar-20' 'Apr-20'
 'May-20' 'Jun-20' 'Jul-20' 'Aug-20' 'Sep-20' 'Oct-20' 'Nov-20' 'Dec-20'
 'Jan-21' 'Feb-21' 'Mar-21' 'Apr-21' 'May-21' 'Jun-21' 'Jul-21' 'Aug-21'
 'Sep-21' 'Oct-21' 'Nov-21' 'Dec-21' 'Jan-22' 'Feb-22' 'Mar-22' 'Apr-22'
 'May-22' 'Jun-22' 'Jul-22' 'Aug-22' 'Sep-22' 'Oct-22' 'Nov-22' 'Dec-22']
Empty DataFrame
Columns: [Date, USD for United Kingdom, USD FOR EURO, USD FOR CANADA]
Index: []

C:\Users\Addisu\AppData\Local\Temp\ipykernel_9724\2092741378.py:25: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  oil['Date'] = pd.to_datetime(oil['Date'])

            Price  USD for United Kingdom  USD FOR EURO  USD FOR CANADA  \
Date
1970-01-31    NaN                     NaN           NaN             NaN
1987-01-01    NaN                0.663305      0.950031        1.360014
1987-02-01    NaN                0.654547      0.933875        1.334195
1987-03-01    NaN                0.628020      0.937658        1.319268
1987-04-01    NaN                0.613089      0.925950        1.320186

            Unemployment  GDP  Infliation
Date
1970-01-31           5.3  3.1         8.0
1987-01-01           5.3  3.1         8.0
1987-02-01           5.3  3.1         8.0
1987-03-01           5.3  3.1         8.0
1987-04-01           5.3  3.1         8.0

C:\Users\Addisu\AppData\Local\Temp\ipykernel_9724\2092741378.py:33: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  macroeconomic_monthly = macroeconomic.resample('M').ffill()
C:\Users\Addisu\AppData\Local\Temp\ipykernel_9724\2092741378.py:39: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  combined_data.fillna(method='ffill', inplace=True)

In [3]:
import pandas as pd
df=pd.read_csv('../Data/combined_data.csv')
df

,Date,Price,USD for United Kingdom,USD FOR EURO,USD FOR CANADA,Unemployment,GDP,Infliation
0,5/20/1987,18.63,0.599826,0.913321,1.341480,5.3,3.1,8
1,5/21/1987,18.45,0.599826,0.913321,1.341480,5.3,3.1,8
2,5/22/1987,18.55,0.599826,0.913321,1.341480,5.3,3.1,8
3,5/25/1987,18.60,0.599826,0.913321,1.341480,5.3,3.1,8
4,5/26/1987,18.63,0.599826,0.913321,1.341480,5.3,3.1,8
...,...,...,...,...,...,...,...,...
9159,11/9/2022,93.05,0.851893,0.980093,1.344536,5.3,3.1,8
9160,11/10/2022,94.25,0.851893,0.980093,1.344536,5.3,3.1,8
9161,11/11/2022,96.37,0.851893,0.980093,1.344536,5.3,3.1,8
9162,11/14/2022,93.59,0.851893,0.980093,1.344536,5.3,3.1,8
9163,12/1/2022,93.59,0.821824,0.944557,1.359291,5.3,3.1,8